[build-system]
requires = ['scikit-build-core', 'pybind11', 'cibuildwheel']
build-backend = 'scikit_build_core.build'

[project]
name = 'evn'
version = '0.1.0'
requires-python = '>=3.9'
dependencies = [
    'assertpy',
    'click',
    'icecream',
    'multipledispatch',
    'PrettyPrintTree',
    'pyyaml',
    'rapidfuzz',
    'rich',
    'ruff',
    'typing_extensions; python_version < "3.10"',
    'wrapt',
]

[project.optional-dependencies]
dev = [
    'pytest',
    'pytest-xdist',
    'pytest-benchmark',
    'pytest-cov',
    'pytest-sugar',
]

[project.scripts]
evn = 'evn.tool.__main__:main'

[tool.pytest.ini_options]
minversion = '8'
addopts = ''
pythonpath = ['.']
testpaths = ['evn/tests']
markers = [
    'slow: marks tests as slow to run',
    'ci: tests that should only run in ci',
]


[tool.ruff]
lint.ignore = [
   'E731', #  [ ] Do not assign a `lambda` expression, use a `def`
   'E402', #  [ ] Module level import not at top of file
   'E741', #  [ ] Ambiguous variable name: `I`
   'E701', #  [ ] Multiple statements on one line (colon)
   'F403', #  [ ] `from Attention_module import *` used; unable to detect undefined names
   'F405',
   'F821',
   'F841',

]
lint.dummy-variable-rgx = '^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?)|ic)$'
line-length = 113
target-version = 'py313'
format.quote-style = 'single'
format.indent-style = 'space'
format.docstring-code-format = true

[tool.pyright]
venvPath = '/home/sheffler/sw/MambaForge/envs'
venv = 'rfdsym312'
# venvPath = /home/sheffler/rfd/lib/evn
# venv = .venv
# defineConstant = { DEBUG = true }
# typeCheckingMode = enhanced
typeCheckingMode = 'standard'
reportMissingImports = true
reportMissingTypeStubs = false
reportUnusedExpression = false
pythonPlatform = 'Linux'
pythonVersion = 3.13
